/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BusinessListing = IDL.Record({
  'startingPrice' : IDL.Nat,
  'about' : IDL.Text,
  'ownerName' : IDL.Text,
  'city' : IDL.Text,
  'businessName' : IDL.Text,
  'category' : IDL.Text,
  'phone' : IDL.Text,
});
export const Lead = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'venueInterest' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllBusinessListings' : IDL.Func(
      [],
      [IDL.Vec(BusinessListing)],
      ['query'],
    ),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'submitBusinessListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'submitLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BusinessListing = IDL.Record({
    'startingPrice' : IDL.Nat,
    'about' : IDL.Text,
    'ownerName' : IDL.Text,
    'city' : IDL.Text,
    'businessName' : IDL.Text,
    'category' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Lead = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'venueInterest' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllBusinessListings' : IDL.Func(
        [],
        [IDL.Vec(BusinessListing)],
        ['query'],
      ),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'submitBusinessListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'submitLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };